### ISSUE TITLE
Check the status generation, which is maybe too trivial, showing "NO_SIGNAL" if a beacon has not been seen for some time

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.beacon.api#56]
- [x] Should NO_SIGNAL become UNKNOWN_STATUS or do we want to add a new value for unknown? Is it possible to get a "no signal" somehow?
- [x] We should use the wording "Status unknown" in all apps, instead of "No Signal"

**OLD COMMENT**

Related to https://github.com/noi-techpark/beacon-suedtirol-administration-android/issues/33

Maybe it is just a bad wording: "Status unknown" or "We have not seen this beacon for x days", would describe it better

**Comment by Piiit** [comment]
Not really a bug, but should be solved to avoid confusion of users

**Comment by noctho** [comment]
changed. see #73
