### ISSUE TITLE
Status "No Signal" wrong

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.beacon.api#60]
By using the Admin App I've noticed that the API returns "NO SIGNAL" when a beacon has been seen in the last 12 months. This is the opposite way like it should be.

**Comment by sseppi** [comment]
Investigating a little bit more the problem I think that the bug is in the following point of the code:

https://github.com/noi-techpark/beacon-suedtirol-api/blob/master/src/main/java/it/bz/beacon/api/model/Beacon.java#L310

I think that the right code should be:

```
if (!hasRecentlySeen()) {
    return Status.NO_SIGNAL;
}
```

@davidebz can you please check this bug?

**Comment by Piiit** [comment]
Seems to be an issue, that is better solved by @davidebz ... I had a look into that and it looks like Davide touched that part of the code in the past.

**Comment by davidebz** [comment]
> Investigating a little bit more the problem I think that the bug is in the following point of the code:
> 
> https://github.com/noi-techpark/beacon-suedtirol-api/blob/master/src/main/java/it/bz/beacon/api/model/Beacon.java#L310
> 
> I think that the right code should be:
> 
> ```
> if (!hasRecentlySeen()) {
>     return Status.NO_SIGNAL;
> }
> ```
> 
> @davidebz can you please check this bug?

Yes, Thomas confirm me that the not (!) was missing!

**Comment by Piiit** [comment]
Done by @sseppi
https://api.beacon.testingmachine.eu/swagger-ui.html

@davidebz 
please test on testingmachine...

**Comment by Piiit** [comment]
We need to wait for the new version of the Admin Android app... Google has it still in review...
