### ISSUE TITLE
Null reference

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.beacon.api#64]
https://github.com/noi-techpark/beacon-suedtirol-api/blob/43ee5790a463709a6aff31dcd59935c8df106a89/src/main/java/it/bz/beacon/api/service/beacon/BeaconService.java#L135

At this point beaconData can only be null

**Comment by Piiit** [comment]
@sseppi FYI

**Comment by noctho** [comment]
I have fixed this with PR #66 .
