### ISSUE TITLE
Missing API key assocciated to groups causes a 401 unauthorized error

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.beacon.api#68]
The error message of the API should be more specific, telling that the API key is missing...

The error gets thrown from the ApiService class inside getBeacons(List<String> ids)...

@davidebz @sseppi 
Should we make that key mandatory for all groups such that this does not happen anymore, or that the DB already throw such an error during creation? Do we have groups without API keys?

This issue causes a never-ending loading spinner inside the admin webapp without an error message. This should also be solved...

**Comment by noctho** [comment]
Do you also recognize this error in the list overview of all beacons or only when you open the details of a beacon? I was only able to reproduce it in the second case.

**Comment by Piiit** [comment]
Only inside the detail view

**Comment by noctho** [comment]
fixed, see #72
