### ISSUE TITLE
Null Pointer Bug?

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.beacon.api#74]
https://github.com/noi-techpark/it.bz.beacon.api/blob/10ecc759d8951816cd68716c15db5e15c6dca8f1/src/main/java/it/bz/beacon/api/service/beacon/BeaconService.java#L172

Hi @noctho
I think at this point we can only have a null pointer exception, right?

**Comment by noctho** [comment]
Yes you are right. Fixed, see #76
