### ISSUE TITLE
Creation of Groups and assignement of beacon

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.beacon.api#77]
since all beacon has to be assigned to a Group we created a set of CSV file. Each CSV file is named with the name of the Group and contains the list of the beacon of the group. You can download the files at the following link:

https://cloud.opendatahub.bz.it/index.php/s/k96gcpmtadJRSTw

- [x] @Piiit gives access to the DB to @davidebz and @noctho

**Comment by Piiit** [comment]
@sseppi LGTM
